<a href="https://colab.research.google.com/github/sivasamy1/data_analytics/blob/main/Open_Artifacts_in_Museum_%2B_XGBoosting_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **PART I**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
!cat /content/drive/MyDrive/data_analytics/MINIPROJECT_8/cstmc-CSV-en.csv | head -10

artifactNumber|ObjectName|GeneralDescription|model|SerialNumber|Manufacturer|ManuCountry|ManuProvince|ManuCity|BeginDate|EndDate|date_qualifier|patent|NumberOfComponents|ArtifactFinish|ContextCanada|ContextFunction|ContextTechnical|group1|category1|subcategory1|group2|category2|subcategory2|group3|category3|subcategory3|material|Length|Width|Height|Thickness|Weight|Diameter|image|thumbnail
1966.0001.001|Cover|PAPER|WESTERN CANADA AIRWAYS LTD.||Unknown|Unknown|||1927||||1||AT THE TIME IT WAS THE WORLD'S MOST NORTHERNLY AIR SERVICE|||Aviation|Commemorative|Stamps & coins|||||||paper|4.5 cm|2.6 cm|||||http://source.techno-science.ca/artifacts-artefacts/images/1966.0001.001.aa.cs.png|http://source.techno-science.ca/artifacts-artefacts/images/1966.0001.001.aa.cs.thumb.png
1966.0002.001|Stamp, postage|PAPER|WESTERN CANADA AIRWAYS LTD.||Unknown|Unknown|||1927||||1|PINK & BLACK ON WHITE||||Aviation|Commemorative|Stamps & coins|||||||paper|3.8 cm|2.7 cm|||||http://source.techno-science.ca/artif

In [ ]:
import pandas as pd
from tabulate import tabulate

df_museun = pd.read_csv('/content/drive/MyDrive/data_analytics/MINIPROJECT_8/cstmc-CSV-en.csv', on_bad_lines='skip', delimiter='|')

print(tabulate(df_museun.head(), headers='keys', tablefmt='github'))

|    | artifactNumber   | ObjectName     | GeneralDescription   | model                        |   SerialNumber | Manufacturer   | ManuCountry   |   ManuProvince |   ManuCity |   BeginDate |   EndDate |   date_qualifier |   patent |   NumberOfComponents | ArtifactFinish                                    | ContextCanada                                              |   ContextFunction |   ContextTechnical | group1   | category1     | subcategory1   |   group2 |   category2 |   subcategory2 |   group3 |   category3 |   subcategory3 | material   | Length   | Width   |   Height |   Thickness |   Weight |   Diameter | image                                                                              | thumbnail                                                                                |
|----|------------------|----------------|----------------------|------------------------------|----------------|----------------|---------------|----------------|------------|-------------|-----------|-

<ipython-input-3-cb91483d5022>:4: DtypeWarning: Columns (9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_museun = pd.read_csv('/content/drive/MyDrive/data_analytics/MINIPROJECT_8/cstmc-CSV-en.csv', on_bad_lines='skip', delimiter='|')


### **1.1 Total # distinct artifactNumber.**
### **Expected Output: Integer Number**


In [ ]:
print('Total # distinct artifactNumber\n', df_museun['artifactNumber'].nunique())

Total # distinct artifactNumber
 107768


### **1.2 Total # distinct ObjectName.**
### **Expected Output: Integer Number**

In [ ]:
print('Total # distinct ObjectName\n', df_museun['ObjectName'].nunique(dropna=False))

Total # distinct ObjectName
 8191


### **1.3 Top 10 artifacts by weight.**
### **Expected Output:**
### **artifactnumber,weight,generaldescripton,rank_weight**



In [ ]:
df_weigth = df_museun[['artifactNumber', 'Weight', 'GeneralDescription']]
df_weigth['rank_weight'] = df_weigth['Weight'].rank(ascending=False)
df_weigth = df_weigth.sort_values(by='rank_weight', ascending=True)
print(tabulate(df_weigth.head(10), headers='keys', tablefmt='github'))

|       | artifactNumber   | Weight   | GeneralDescription                                                                                                                                                                                                                                                                                      |   rank_weight |
|-------|------------------|----------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------|
| 96491 | 2005.0060.001    | 990 kg   | metal, synthetic and glass components.                                                                                                                                                                                                                      

<ipython-input-6-7d75e644538e>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_weigth['rank_weight'] = df_weigth['Weight'].rank(ascending=False)


### **1.4 Top 10 artifacts by height.**
### **Expected Output:**
### **artifactnumber,height,generaldescripton,rank_height**


In [ ]:
df_heigth = df_museun[['artifactNumber', 'Height', 'GeneralDescription']]
df_heigth['rank_height'] = df_heigth['Height'].rank(ascending=False)
df_heigth = df_heigth.sort_values(by='rank_height', ascending=True)
print(tabulate(df_heigth.head(10), headers='keys', tablefmt='github'))

<ipython-input-7-35465d1c0718>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_heigth['rank_height'] = df_heigth['Height'].rank(ascending=False)


|       | artifactNumber   | Height   | GeneralDescription                                                                                                                                                                                                                                                                                      |   rank_height |
|-------|------------------|----------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------|
|   988 | 1966.0601.001    | 99.8 cm  | WOODEN CABINET; FABRIC SPEAKER COVER; SYNTHETIC TUNING DIALS, BUTTONS, TUNINGINDICATOR PANEL & MOUNTING. GLASS, METAL & SYNTHETIC COMPONENT PARTS; SHEET STEEL CHASSIS                                                                                      

### **1.5 Top 10 category1 by total # artifacts.**
### **Expected Output:**
### **category1,num_artifactNumber, rank_category1**


In [ ]:
df_catgory1 = df_museun.groupby(['category1']).size().to_frame('num_artifactNumber')
df_catgory1['rank_category1'] = df_catgory1['num_artifactNumber'].rank(ascending=False)
df_catgory1 = df_catgory1.sort_values(by='rank_category1', ascending=True).reset_index()
print(tabulate(df_catgory1.head(10), headers='keys', tablefmt='github'))

|    | category1                |   num_artifactNumber |   rank_category1 |
|----|--------------------------|----------------------|------------------|
|  0 | Printed specimens        |                 4270 |                1 |
|  1 | Commemorative            |                 4167 |                2 |
|  2 | Archives                 |                 3026 |                3 |
|  3 | Tools & equipment-trades |                 2730 |                4 |
|  4 | Miscellaneous            |                 2589 |                5 |
|  5 | Clothing                 |                 2008 |                6 |
|  6 | Radio                    |                 1791 |                7 |
|  7 | Cycles & cycling         |                 1440 |                8 |
|  8 | Instruments              |                 1370 |                9 |
|  9 | Food processing          |                 1327 |               10 |


### **1.6 Top 10 BeingDate by # artifactNumber**
### **Expected Output:**
### **begindate,num_artifactnumber,rank_begindate**


In [ ]:
df_begin = df_museun.groupby(['BeginDate']).size().to_frame('num_artifactNumber')
df_begin['rank_BeginDate'] = df_begin['num_artifactNumber'].rank(ascending=False)
df_begin = df_begin.sort_values(by='rank_BeginDate', ascending=True).reset_index()
print(tabulate(df_begin.head(10), headers='keys', tablefmt='github'))

|    |   BeginDate |   num_artifactNumber |   rank_BeginDate |
|----|-------------|----------------------|------------------|
|  0 |        1900 |                 2609 |                1 |
|  1 |        1950 |                 1477 |                2 |
|  2 |        1920 |                 1214 |                3 |
|  3 |        1930 |                 1176 |                4 |
|  4 |        1940 |                 1026 |                5 |
|  5 |        1960 |                  904 |                6 |
|  6 |        1970 |                  883 |                7 |
|  7 |        1910 |                  600 |                8 |
|  8 |        1980 |                  549 |                9 |
|  9 |        1944 |                  548 |               10 |


### **1.7 Top 10 material by # artifactNumber**
### **Expected Output:**
### **material,num_artifactnumber_mat,rank_material**


In [ ]:
df_material = df_museun.groupby(['material']).size().to_frame('num_artifactNumber')
df_material['rank_material'] = df_material['num_artifactNumber'].rank(ascending=False)
df_material = df_material.sort_values(by='rank_material', ascending=True).reset_index()
print(tabulate(df_material.head(10), headers='keys', tablefmt='github'))

|    | material          |   num_artifactNumber |   rank_material |
|----|-------------------|----------------------|-----------------|
|  0 | paper             |                 9394 |               1 |
|  1 | metal             |                 7421 |               2 |
|  2 | glass             |                 2044 |               3 |
|  3 | metal;synthetic   |                 2027 |               4 |
|  4 | synthetic         |                 1663 |               5 |
|  5 | metal->steel      |                 1523 |               6 |
|  6 | synthetic;metal   |                 1386 |               7 |
|  7 | paper->card stock |                 1353 |               8 |
|  8 | metal->brass      |                 1212 |               9 |
|  9 | wood;metal        |                 1175 |              10 |


### **1.8 Merge 3 and 4 on their corresponding rank columns**
### **Expected Output:**
### **rank, w_artifactnumber,h_artifactnumber, weight, height**


In [ ]:
df_merge = df_weigth.merge(df_heigth, on='artifactNumber')
df_merge = df_merge.sort_values(by='rank_weight', ascending=True)
print(tabulate(df_merge.head(), headers='keys', tablefmt='github'))

|    | artifactNumber   | Weight   | GeneralDescription_x                            |   rank_weight | Height   | GeneralDescription_y                            |   rank_height |
|----|------------------|----------|-------------------------------------------------|---------------|----------|-------------------------------------------------|---------------|
|  0 | 2005.0060.001    | 990 kg   | metal, synthetic and glass components.          |           1   | 136.0 cm | metal, synthetic and glass components.          |       30761   |
|  1 | 1981.0613.001    | 952.5 kg | METAL & WOOD                                    |           2   | 197.0 cm | METAL & WOOD                                    |       25941   |
|  2 | 1968.0102.001    | 950 kg   | nan                                             |           4.5 | 161.0 cm | nan                                             |       28108.5 |
|  3 | 1967.0027.001    | 950 kg   | nan                                             |           4.5

### **1.9 Top 10 group by # artifactNumber**
### **Expected Output:**
### **group,num_artifactnumber_group,rank_group**


In [ ]:
df_museun['group'] = df_museun['group1'].fillna(df_museun['group2'])
df_museun['group'] = df_museun['group'].fillna(df_museun['group3'])
df_group = df_museun.groupby(['group']).size().to_frame('num_artifactnumber_group')
df_group['rank_group'] = df_group['num_artifactnumber_group'].rank(ascending=False)
df_group = df_group.sort_values(by='rank_group', ascending=True).reset_index()
print(tabulate(df_group.head(10), headers='keys', tablefmt='github'))

|    | group                 |   num_artifactnumber_group |   rank_group |
|----|-----------------------|----------------------------|--------------|
|  0 | Aviation              |                      12366 |            1 |
|  1 | Communications        |                       6579 |            2 |
|  2 | Printing              |                       6290 |            3 |
|  3 | Industrial Technology |                       5616 |            4 |
|  4 | Photography           |                       5067 |            5 |
|  5 | Medical Technology    |                       4445 |            6 |
|  6 | Agriculture           |                       3595 |            7 |
|  7 | Domestic Technology   |                       2817 |            8 |
|  8 | Physics               |                       2636 |            9 |
|  9 | Vacuum Tubes          |                       2084 |           10 |


### **1.10 Top 10 subcategory1 by total # artifacts.**
### **Expected Output:**
### **subcategory1,num_artifactNumber, rank_subcategory1**


In [ ]:
df_sub1 = df_museun.groupby(['subcategory1']).size().to_frame('num_artifactNumber')
df_sub1['rank_subcategory1'] = df_sub1['num_artifactNumber'].rank(ascending=False)
df_sub1 = df_sub1.sort_values(by='rank_subcategory1', ascending=True).reset_index()
print(tabulate(df_sub1.head(10), headers='keys', tablefmt='github'))

|    | subcategory1             |   num_artifactNumber |   rank_subcategory1 |
|----|--------------------------|----------------------|---------------------|
|  0 | Memorabilia              |                 2470 |                   1 |
|  1 | Miscellaneous            |                 1876 |                   2 |
|  2 | Art                      |                 1324 |                   3 |
|  3 | Receivers & transmitters |                 1248 |                   4 |
|  4 | Tools                    |                 1169 |                   5 |
|  5 | Harness & saddle maker   |                 1091 |                   6 |
|  6 | Accessories              |                 1081 |                   7 |
|  7 | Passenger                |                 1015 |                   8 |
|  8 | Food preparation         |                 1003 |                   9 |
|  9 | Surgical                 |                  962 |                  10 |


### **1.11 Merge 7 and 9 on their corresponding rank columns**
### **Expected Output:**
### **material, num_artifactnumber_mat, rank, group, num_artifactnumber_group**


In [ ]:
df_merge1 = pd.merge(df_material, df_group, left_on='rank_material', right_on='rank_group')
df_merge2 = df_merge1.drop('rank_group', axis=1, inplace=True)
df_merge2 = df_merge1.rename(columns={'num_artifactNumber': 'num_artifactnumber_mat', 'rank_material': 'rank'}, inplace=True)
print(tabulate(df_merge1.head(10), headers='keys', tablefmt='github'))

|    | material          |   num_artifactnumber_mat |   rank | group                 |   num_artifactnumber_group |
|----|-------------------|--------------------------|--------|-----------------------|----------------------------|
|  0 | paper             |                     9394 |      1 | Aviation              |                      12366 |
|  1 | metal             |                     7421 |      2 | Communications        |                       6579 |
|  2 | glass             |                     2044 |      3 | Printing              |                       6290 |
|  3 | metal;synthetic   |                     2027 |      4 | Industrial Technology |                       5616 |
|  4 | synthetic         |                     1663 |      5 | Photography           |                       5067 |
|  5 | metal->steel      |                     1523 |      6 | Medical Technology    |                       4445 |
|  6 | synthetic;metal   |                     1386 |      7 | Agricultu

## **PART II**

### **2.1 Credit Card Fraud Detection: Credit Card Fraud classification using XGBOOST Column value to be classified is in column "Is_fraud" and all other columns are the features. Use two-fold cross validation and evaluation metrics: Precision, Recall, F1-score, Accuracy [wiki]. Also print confusion matrix [wiki]. Refer basic notebook template for some code and also internet. Feature importance is a concept used in machine learning to understand the relative importance or contribution of different features (also known as input variables or predictors) towards predicting the target variable. It helps in understanding which features have the most influence on the model's predictions. For Random Forest or Gradient Boosting, feature importance scores can be calculated based on how often a feature is used to make decisions that result in a reduction in impurity (e.g., Gini impurity or entropy) across all the trees in the ensemble.**

In [18]:
import pandas as pd
import numpy as np
from tabulate import tabulate
from xgboost import XGBClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, confusion_matrix

In [19]:
chunk_size = 10000
data_chunks = pd.read_csv("/content/drive/MyDrive/data_analytics/MINIPROJECT_7/fraud test.csv", chunksize=chunk_size)

metrics = {"precision": [], "recall": [], "f1_score": [], "accuracy": [], "conf_matrix": []}
model = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='binary:logistic')
kf = KFold(n_splits=2, shuffle=True, random_state=42)

for chunk in data_chunks:
    chunk = pd.get_dummies(chunk, dtype='int')
    X = chunk.drop(columns=["is_fraud"])
    y = chunk["is_fraud"]

    for train_index, test_index in kf.split(X):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        metrics["precision"].append(precision_score(y_test, y_pred))
        metrics["recall"].append(recall_score(y_test, y_pred))
        metrics["f1_score"].append(f1_score(y_test, y_pred))
        metrics["accuracy"].append(accuracy_score(y_test, y_pred))
        metrics["conf_matrix"].append(confusion_matrix(y_test, y_pred))


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.p

In [20]:
print("Average Precision:", np.mean(metrics["precision"]))
print("Average Recall:", np.mean(metrics["recall"]))
print("Average F1-score:", np.mean(metrics["f1_score"]))
print("Average Accuracy:", np.mean(metrics["accuracy"]))


Average Precision: 0.7061842353581939
Average Recall: 0.27188912220015415
Average F1-score: 0.3519315898478864
Average Accuracy: 0.9967446428571429


In [21]:

for i, cm in enumerate(metrics["conf_matrix"], 1):
    print(f"Confusion Matrix - Fold {i}:\n", cm)

Confusion Matrix - Fold 1:
 [[4991    0]
 [   6    3]]
Confusion Matrix - Fold 2:
 [[4985    2]
 [   9    4]]
Confusion Matrix - Fold 3:
 [[4972    0]
 [  20    8]]
Confusion Matrix - Fold 4:
 [[4982    0]
 [  15    3]]
Confusion Matrix - Fold 5:
 [[4963    9]
 [  18   10]]
Confusion Matrix - Fold 6:
 [[4966    0]
 [  29    5]]
Confusion Matrix - Fold 7:
 [[4978    0]
 [  18    4]]
Confusion Matrix - Fold 8:
 [[4983    1]
 [   9    7]]
Confusion Matrix - Fold 9:
 [[4982    3]
 [  10    5]]
Confusion Matrix - Fold 10:
 [[4984    0]
 [  15    1]]
Confusion Matrix - Fold 11:
 [[4976    0]
 [  19    5]]
Confusion Matrix - Fold 12:
 [[4972    0]
 [  21    7]]
Confusion Matrix - Fold 13:
 [[4985    0]
 [  14    1]]
Confusion Matrix - Fold 14:
 [[4988    0]
 [   8    4]]
Confusion Matrix - Fold 15:
 [[4987    0]
 [  11    2]]
Confusion Matrix - Fold 16:
 [[4988    0]
 [   9    3]]
Confusion Matrix - Fold 17:
 [[4951   18]
 [  15   16]]
Confusion Matrix - Fold 18:
 [[4955   11]
 [  20   14]]
C